=== amaneux/aicon-tos-mediator/src/main/resources/conf/mediator/schema/connect-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2023 sp1 (x64) (http://www.altova.com) by Ron de Waard (Twinspot BV) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Define the root element Config -->
	<xs:element name="Config">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="General"/>
				<xs:element name="Datasources" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="Mongo" type="ConfigGroupType"/>
							<xs:element name="SqlDb" type="ConfigGroupType"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Connections" minOccurs="0"/>
				<xs:element ref="Flows" minOccurs="0"/>
				<xs:element ref="TosControl" minOccurs="0"/>
				<xs:element ref="Interceptors" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
		<!-- Define keys for Http and Kafka "name" attributes -->
		<xs:key name="HttpKey">
			<xs:selector xpath=".//Http"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:key name="KafkaKey">
			<xs:selector xpath=".//Kafka"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<!-- Key references for Http and Kafka elements with "ref" -->
		<xs:keyref name="HttpRef" refer="HttpKey">
			<xs:selector xpath=".//HttpRef"/>
			<xs:field xpath="@ref"/>
		</xs:keyref>
		<xs:keyref name="KafkaRef" refer="KafkaKey">
			<xs:selector xpath=".//KafkaRef"/>
			<xs:field xpath="@ref"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="ConfigGroupType">
		<xs:annotation>
			<xs:documentation>Type to define ConfigGroup element tree</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ConfigItem" type="ConfigItemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ConfigGroup" type="ConfigGroupType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:complexType name="ConfigItemType">
		<xs:annotation>
			<xs:documentation>Type defining a single ConfigItem</xs:documentation>
		</xs:annotation>
		<xs:attribute name="key" type="ConfigItemKeyEnum" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="comment" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="ConfigItemKeyEnum">
		<xs:annotation>
			<xs:documentation> Enumeration for ConfigItem key attribute </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="bootstrap.servers"/>
			<xs:enumeration value="canary.cdc.frequency"/>
			<xs:enumeration value="canary.interval.ms"/>
			<xs:enumeration value="canary.on.off"/>
			<xs:enumeration value="cdc.threshold"/>
			<xs:enumeration value="cdc.topic.prefix"/>
			<xs:enumeration value="class.name"/>
			<xs:enumeration value="collection.move_info"/>
			<xs:enumeration value="connection.timeout.ms"/>
			<xs:enumeration value="decking.engine.request.topic"/>
            <xs:enumeration value="decking.engine.request.topic.allow.create"/>
            <xs:enumeration value="decking.engine.response.topic"/>
            <xs:enumeration value="decking.engine.response.topic.allow.create"/>
			<xs:enumeration value="email.hostname"/>
			<xs:enumeration value="email.password"/>
			<xs:enumeration value="email.sender"/>
			<xs:enumeration value="email.smtpport"/>
			<xs:enumeration value="email.username"/>
			<xs:enumeration value="environment.name"/>
			<xs:enumeration value="field.id"/>
			<xs:enumeration value="field.type"/>
			<xs:enumeration value="group.id"/>
			<xs:enumeration value="hostport"/>
			<xs:enumeration value="hostname"/>
			<xs:enumeration value="http.connect.timeout.ms"/>
			<xs:enumeration value="http.content.type"/>
			<xs:enumeration value="http.method"/>
			<xs:enumeration value="http.password"/>
			<xs:enumeration value="http.read.timeout.ms"/>
			<xs:enumeration value="http.url"/>
			<xs:enumeration value="http.username"/>
			<xs:enumeration value="max.messages.in.storage"/>
			<xs:enumeration value="max.time.in.storage"/>
			<xs:enumeration value="password"/>
			<xs:enumeration value="poll.timeout.ms"/>
			<xs:enumeration value="processing.delay"/>
			<xs:enumeration value="schema.registry.port"/>
			<xs:enumeration value="terminal.name"/>
			<xs:enumeration value="test.changes"/>
			<xs:enumeration value="test.creations"/>
			<xs:enumeration value="test.deletions"/>
			<xs:enumeration value="topic.name"/>
			<xs:enumeration value="topic.response.fail"/>
			<xs:enumeration value="topic.response.ok"/>
            <xs:enumeration value="topic.source"/>
            <xs:enumeration value="topic.allow.create"/>
            <xs:enumeration value="tos.position.schema"/>
			<xs:enumeration value="transformer.class"/>
			<xs:enumeration value="transformer.request"/>
			<xs:enumeration value="transformer.response"/>
			<xs:enumeration value="url.path"/>
			<xs:enumeration value="username"/>
			<xs:enumeration value="yard.scope"/>
			<xs:enumeration value="key.conversion.prefix"/>
			<xs:enumeration value="block.conversion"/>
			<xs:enumeration value="row.conversion"/>
			<xs:enumeration value="bay.conversion"/>
			<xs:enumeration value="tier.conversion"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ConfigItem">
		<xs:annotation>
			<xs:documentation> ConfigItem element with enumeration </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="key" type="ConfigItemKeyEnum" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="comment" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TosControl">
		<xs:annotation>
			<xs:documentation> TosControl element definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CanaryCheck"/>
				<xs:element ref="ControlRequest"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="General">
		<xs:annotation>
			<xs:documentation>General definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GeneralItems" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GeneralItems">
		<xs:annotation>
			<xs:documentation>General items</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Connections">
		<xs:annotation>
			<xs:documentation> Connections element definition </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Kafka"/>
				<xs:element ref="Http"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="Kafka">
		<xs:annotation>
			<xs:documentation> Kafka element definition </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Http">
		<xs:annotation>
			<xs:documentation> Http element definition with ref attribute </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Flows">
		<xs:annotation>
			<xs:documentation> Flows element definition </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Flow" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Flow">
		<xs:annotation>
			<xs:documentation> Flow element definition </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="ConfigItem"/>
					<xs:element ref="HttpRef"/>
					<xs:element ref="KafkaRef"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="HttpRef">
		<xs:annotation>
			<xs:documentation> HttpRef element definition to reference Http by "ref" attribute only </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="ref" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="KafkaRef">
		<xs:annotation>
			<xs:documentation> KafkaRef element definition to reference Kafka by "ref" attribute only </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="ref" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CanaryCheck">
		<xs:annotation>
			<xs:documentation> CanaryCheck with Http reference </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
				<xs:element ref="CDCTable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="HttpRef"/>
				<xs:element ref="KafkaRef"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ControlRequest">
		<xs:annotation>
			<xs:documentation> ControlRequest element with an HttpRef reference </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
				<xs:element ref="HttpRef"/>
				<xs:element ref="KafkaRef"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CDCTable">
		<xs:annotation>
			<xs:documentation> CDCTableTopic element </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Interceptors">
		<xs:annotation>
			<xs:documentation> Topics element </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InterceptorEntity" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="InterceptorEntity">
		<xs:annotation>
			<xs:documentation> Topic element </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConfigItem" maxOccurs="unbounded"/>
				<xs:element name="Scenarios" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Scenario" type="ConfigGroupType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== amaneux/aicon-tos-mediator/src/test/resources/conf/mediator/flowmanagertest-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema/connect-configuration.xsd">
    <General>
        <GeneralItems>
            <ConfigItem key="terminal.name" value="HVR" comment="Name of port"/>
            <ConfigItem key="environment.name" value="TST" comment="N4 installation"/>
            <ConfigItem key="yard.scope" value="YYY/XXX/ZZZ/WWW" comment=""/>
            <ConfigItem key="email.hostname" value="smtp.gmail.com" comment=""/>
            <ConfigItem key="email.smtpport" value="587" comment=""/>
            <ConfigItem key="email.username" value="harrievanrijn@gmail.com" comment=""/>
            <ConfigItem key="email.password" value="aueq vucf nptt tihl" comment=""/>
            <ConfigItem key="email.sender" value="harrievanrijn@gmail.com" comment=""/>
        </GeneralItems>
    </General>
    <Connections>
        <Kafka name="KAFKA">
            <ConfigItem key="hostname" value="localhost" comment="Hostname/IP-address of the kafka broker"/>
            <ConfigItem key="hostport" value="9092,9093,9094"/>
            <ConfigItem key="schema.registry.port" value="8081" comment="The port number of the schema registry"/>
            <ConfigItem key="connection.timeout.ms" value="10000" comment="Max time it may to take to connect"/>
            <ConfigItem key="group.id" value="aicon-tos-mediator" comment="Group id allows multiple consumers to read in parallel"/>
            <ConfigItem key="poll.timeout.ms" value="1000" comment="Time for every poll session of the kafka stream"/>
            <ConfigItem key="cdc.topic.prefix" value="tos.test7" comment="The prefix to every tos-table given by the cdc connector." />
        </Kafka>
        <Http name="HTTP_SEND">
            <ConfigItem key="http.url" value="http://remote_webserver:8080/junit/api" comment="The URL of the HTTP receiver."/>
            <ConfigItem key="http.method" value="POST" comment="The method to use for sending."/>
            <ConfigItem key="http.content.type" value="xml" comment="The content type used for sending."/>
            <ConfigItem key="http.connect.timeout.ms" value="5000" comment="The time it may take for connecting."/>
            <ConfigItem key="http.read.timeout.ms" value="10000" comment="The time it may take for reading (incl.connection time)."/>
        </Http>
        <Http name="HTTP_TEMPLATE">
            <ConfigItem key="http.url" value="http://&lt;IP-address&gt;:&lt;port&gt;/&lt;common-path&gt;/" comment="The URL of the HTTP receiver."/>
            <ConfigItem key="http.method" value="POST" comment="The method to use for sending."/>
            <ConfigItem key="http.content.type" value="xml" comment="The content type used for sending."/>
            <ConfigItem key="http.connect.timeout.ms" value="5000" comment="The time it may take for connecting."/>
            <ConfigItem key="http.read.timeout.ms" value="10000" comment="The time it may take for reading (incl.connection time)."/>
        </Http>
        <Http name="TOS-N4">
            <ConfigItem key="http.url" value="http://localhost:8282/aico-tos-connect/basicXMLWebService" comment="The URL of the HTTP receiver." />
            <!--
            <ConfigItem key="http.url" value="http://n4-webservice-node:9081/argo/basicXMLWebService" comment="The URL of the HTTP receiver." />
            -->
            <ConfigItem key="http.method" value="POST" comment="The method to use for sending." />
            <ConfigItem key="http.content.type" value="xml" comment="The content type used for sending."/>
            <ConfigItem key="http.connect.timeout.ms" value="5000" comment="The time it may take for connecting." />
            <ConfigItem key="http.read.timeout.ms" value="10000" comment="The time it may take for reading (incl.connection time)." />
            <ConfigItem key="transformer.class" value="com.aicon.tos.connect.http.transformers.SoapTransformer"
                                                                        comment="Transformer class to wrap the request and strip the response."/>
        </Http>
    </Connections>
    <Flows>
        <Flow name="FLOW_1">
            <ConfigItem key="url.path" value="" comment="Extends the path of the connection URL"/>
            <ConfigItem key="topic.source" value="" comment="The source topic to subscribe to"/>
            <ConfigItem key="topic.response.ok" value="" comment="The response topic to send to when a response has been received"/>
            <ConfigItem key="topic.response.fail" value="" comment="The response topic to send to when connection failed (when empty, the ok respone top[ic will be used."/>
            <ConfigItem key="transformer.request" value="" comment="The transformer full classname (available on the classpath) to transform the request into a message the TOS accepts."/>
            <ConfigItem key="transformer.response" value="" comment="The transformer full classname (available on the classpath) to transform the response into a message Avlino accepts."/>
            <HttpRef ref="HTTP_SEND"/>
            <KafkaRef ref="KAFKA"/>
        </Flow>
        <Flow name="FLOW_2">
            <ConfigItem key="url.path" value="" comment="Extends the path of the connection URL"/>
            <ConfigItem key="topic.source" value="" comment="The source topic to subscribe to"/>
            <ConfigItem key="topic.response.ok" value="" comment="The response topic to send to when a response has been received"/>
            <ConfigItem key="topic.response.fail" value="" comment="The response topic to send to when connection failed (when empty, the ok respone top[ic will be used."/>
            <ConfigItem key="transformer.request" value="" comment="The transformer full classname (available on the classpath) to transform the request into a message the TOS accepts."/>
            <ConfigItem key="transformer.response" value="" comment="The transformer full classname (available on the classpath) to transform the response into a message Avlino accepts."/>
            <HttpRef ref="HTTP_SEND"/>
            <KafkaRef ref="KAFKA"/>
        </Flow>
        <Flow name="ControlFlow">
            <ConfigItem key="topic.source" value="AICON_TOS_CONTROL" comment="The source topic to subscribe to"/>
            <ConfigItem key="topic.response.ok" value="AICON_TOS_CONTROL_MESSAGE"
                        comment="The response topic to send to when a response has been received"/>
            <ConfigItem key="topic.response.fail" value=""
                        comment="The response topic to send to when connection failed (when empty, the ok response topic will be used."/>
            <ConfigItem key="transformer.request" value=""
                        comment="The transformer full classname (available on the classpath) to transform the request into a message the TOS accepts."/>
            <ConfigItem key="transformer.response" value=""
                        comment="The transformer full classname (available on the classpath) to transform the response into a message Avlino accepts."/>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="KAFKA"/>
        </Flow>
    </Flows>
    <TosControl>
        <CanaryCheck name="Canary Check">
            <ConfigItem key="canary.on.off" value="off"/>
            <ConfigItem key="canary.interval.ms" value="12000"/>
            <ConfigItem key="canary.cdc.frequency" value="6"/>
            <CDCTable name="inv_move_event">
                <ConfigItem key="topic.name" value="INV_MOVE_EVENT_MV"/>
                <ConfigItem key="cdc.threshold" value="50000"/>
            </CDCTable>
            <CDCTable name="inv_unit_fcy_visit">
                <ConfigItem key="topic.name" value="INV_UNIT_FCY_VISIT_MV"/>
                <ConfigItem key="cdc.threshold" value="50000"/>
            </CDCTable>
            <CDCTable name="inv_wi">
                <ConfigItem key="topic.name" value="INV_WI_MV"/>
                <ConfigItem key="cdc.threshold" value="50000"/>
            </CDCTable>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="KAFKA"/>
        </CanaryCheck>
        <ControlRequest name="Control Request">
            <ConfigItem key="topic.source" value="aicon_tos_control" comment="tobefilled"/>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="KAFKA"/>
        </ControlRequest>
    </TosControl>
</Config>

=== amaneux/aicon-tos-mediator/src/main/resources/conf/mediator/LOCAL-DEV-aicon-connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- =========================================== -->
<!-- Configuration file for Virginia Development -->
<!-- =========================================== -->
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema/connect-configuration.xsd">
    <General>
        <GeneralItems>
            <ConfigItem key="terminal.name" value="LOCAL" comment="Name of port"/>
            <ConfigItem key="environment.name" value="DEV"
                        comment="Environment should match env within the mediator hostname"/>
            <ConfigItem key="yard.scope" value="VIT/VIT/VIG/PTM" comment="N4-scope: operator/complex/facility/yard"/>
            <ConfigItem key="tos.position.schema" value="B3R3C1.T1"
                        comment="Label schema, using: B=Block, R=Row, C=Column, T=Tier"/>
            <ConfigItem key="email.hostname" value="smtp.gmail.com" comment=""/>
            <ConfigItem key="email.smtpport" value="587" comment=""/>
            <ConfigItem key="email.username" value="harrievanrijn@gmail.com" comment=""/>
            <ConfigItem key="email.password" value="aueq vucf nptt tihl" comment=""/>
            <ConfigItem key="email.sender" value="harrievanrijn@gmail.com" comment=""/>
            <ConfigItem key="decking.engine.request.topic" value="aicon_decking_request_v2"/>
            <ConfigItem key="decking.engine.response.topic" value="aicon_decking_response_v2"/>
        </GeneralItems>
    </General>
    <Connections>
        <Kafka name="TOS-KAFKA">
            <ConfigItem key="hostname" value="localhost"
                        comment="Hostname/IP-address of the kafka broker"/> <!-- ipc localhost -->
            <ConfigItem key="hostport" value="9092" comment=""/>
            <ConfigItem key="schema.registry.port" value="8081" comment="The port number of the schema registry"/>
            <ConfigItem key="connection.timeout.ms" value="10000" comment="Max time it may to take to connect"/>
            <ConfigItem key="group.id" value="aicon-tos-mediator"
                        comment="Group id allows multiple consumers to read in parallel"/>
            <ConfigItem key="poll.timeout.ms" value="1000" comment="Time for every poll session of the kafka stream"/>
            <ConfigItem key="cdc.topic.prefix" value="bool_oracle_Num_lowercase_1.CDC_USER."
                        comment="The prefix to every tos-table given by the cdc connector."/>
        </Kafka>
        <Http name="TOS-N4">
            <ConfigItem key="http.url" value="http://10.111.212.43:9081/apex/services/argobasicservice"
                        comment="The URL of the HTTP receiver."/>
            <ConfigItem key="http.username" value="admin" comment="The method to use for sending."/>
            <ConfigItem key="http.password" value="admin" comment="The method to use for sending."/>
            <ConfigItem key="http.method" value="POST" comment="The method to use for sending."/>
            <ConfigItem key="http.content.type" value="xml" comment="The content type used for sending."/>
            <ConfigItem key="http.connect.timeout.ms" value="5000" comment="The time it may take for connecting."/>
            <ConfigItem key="http.read.timeout.ms" value="10000"
                        comment="The time it may take for reading (incl.connection time)."/>
            <ConfigItem key="transformer.class" value="com.aicon.tos.connect.http.transformers.SoapTransformer"
                        comment="Transformer class to wrap the request and strip the response."/>
        </Http>
    </Connections>
    <Flows>
        <Flow name="ControlFlow">
            <ConfigItem key="topic.source" value="AICON_TOS_CONTROL" comment="The source topic to subscribe to"/>
            <ConfigItem key="topic.response.ok" value="aicon_tos_control_response"
                        comment="The response topic to send to when a response has been received"/>
            <ConfigItem key="topic.response.fail" value=""
                        comment="The response topic to send to when connection failed (when empty, the ok response topic will be used."/>
            <ConfigItem key="transformer.request" value=""
                        comment="The transformer full classname (available on the classpath) to transform the request into a message the TOS accepts."/>
            <ConfigItem key="transformer.response" value=""
                        comment="The transformer full classname (available on the classpath) to transform the response into a message Avlino accepts."/>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="TOS-KAFKA"/>
        </Flow>
        <Flow name="DeckingUpdateFlow">
            <ConfigItem key="topic.source" value="TOS_DECKING_UPDATE_REQUEST"
                        comment="The source topic to subscribe to"/>
            <ConfigItem key="topic.response.ok" value="TOS_DECKING_UPDATE_RESPONSE"
                        comment="The response topic to send to when a response has been received"/>
            <ConfigItem key="topic.response.fail" value=""
                        comment="The response topic to send to when connection failed (when empty, the ok response topic will be used."/>
            <ConfigItem key="transformer.request" value=""
                        comment="The transformer full classname (available on the classpath) to transform the request into a message the TOS accepts."/>
            <ConfigItem key="transformer.response" value=""
                        comment="The transformer full classname (available on the classpath) to transform the response into a message Avlino accepts."/>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="TOS-KAFKA"/>
        </Flow>
    </Flows>
    <TosControl>
        <CanaryCheck name="Canary Check">
            <ConfigItem key="canary.on.off" value="off"/>
            <ConfigItem key="canary.interval.ms" value="12000"/>
            <ConfigItem key="canary.cdc.frequency" value="6"/>
            <CDCTable name="inv_move_event">
                <ConfigItem key="topic.name" value="INV_MOVE_EVENT_MV"/>
                <ConfigItem key="group.id" value="aicon-tos-mediator"/>
                <ConfigItem key="cdc.threshold" value="5000"/>
            </CDCTable>
            <!--            <CDCTable name="inv_unit_fcy_visit">-->
            <!--                <ConfigItem key="topic.name" value="INV_UNIT_FCY_VISIT_MV"/>-->
            <!--                <ConfigItem key="group.id" value="aicon-tos-mediator"/>-->
            <!--                <ConfigItem key="cdc.threshold" value="40000"/>-->
            <!--            </CDCTable>-->
            <CDCTable name="inv_wi">
                <ConfigItem key="topic.name" value="INV_WI_MV"/>
                <ConfigItem key="group.id" value="aicon-tos-mediator"/>
                <ConfigItem key="cdc.threshold" value="4000"/>
            </CDCTable>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="TOS-KAFKA"/>
        </CanaryCheck>
        <ControlRequest name="Control Request">  <!-- unused??? -->
            <ConfigItem key="topic.source" value="aicon_tos_control" comment="tobefilled"/>
            <ConfigItem key="group.id" value="aicon-tos-mediator-controlflow"/>
            <HttpRef ref="TOS-N4"/>
            <KafkaRef ref="TOS-KAFKA"/>
        </ControlRequest>
    </TosControl>
    <Interceptors>
        <InterceptorEntity name="inv_wi">
            <ConfigItem key="topic.name" value="ORDERS" comment=""/>
            <ConfigItem key="max.messages.in.storage" value="10000" comment=""/>
            <ConfigItem key="max.time.in.storage" value="30" comment=""/>
            <ConfigItem key="processing.delay" value="2000" comment=""/>
            <ConfigItem key="test.creations" value="false" comment=""/>
            <ConfigItem key="test.changes" value="false" comment=""/>
            <ConfigItem key="test.deletions" value="false" comment=""/>
        </InterceptorEntity>
        <InterceptorEntity name="truck_transactions">
            <ConfigItem key="topic.name" value="truck_transactions" comment=""/>
            <ConfigItem key="max.messages.in.storage" value="5000" comment=""/>
            <ConfigItem key="max.time.in.storage" value="30" comment=""/>
            <ConfigItem key="processing.delay" value="1500" comment=""/>
            <ConfigItem key="test.creations" value="true" comment=""/>
            <ConfigItem key="test.changes" value="false" comment=""/>
            <ConfigItem key="test.deletions" value="false" comment=""/>
        </InterceptorEntity>
    </Interceptors>
</Config>
